[project]
name = "SWCD-Tools"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arcpy>=3.3",
    "numpy>=1.24.3",
    "openpyxl>=3.0.10",
    "packaging>=23.2",
    "scipy>=1.9.3",
]

[dependency-groups]
dev = [
    "ty>=0.0.51",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
exclude-newer = "30 days"

[tool.ty.environment]
python-version = "3.11" # target 3.11 for arcpy >=3.3 compatibility

[tool.ty.rules]
unresolved-import = "ignore"
unresolved-attribute = "ignore"
possibly-missing-submodule = "ignore"

[tool.ruff]
line-length = 100

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
ignore = [
    "BLE001",
    "N999",
    "SIM208",
    "PYI041",
    "E501",
    "RUF015",
]
